version: "3.9"
services:
  app:
    build:
      context: .
      target: develop
      dockerfile: Dockerfile_dev
    volumes:
      - type: bind
        source: "src"
        target: "/app/src"
      - type: bind
        source: "Cargo.toml"
        target: "/app/Cargo.toml"
      - type: bind
        source: "Cargo.lock"
        target: "/app/Cargo.lock"
      - type: bind
        source: "index.html"
        target: "/app/index.html"
    healthcheck:
      test: "curl -f http://localhost:8080"
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    ports:
      - 8080:8080
